### ISSUE TITLE
Placement of this in curriculum feels weird

### ISSUE THREAD

**Issue by wlycdgr** [learn-co-curriculum/how-the-web-works-readme#11]
The previous couple units (OO Ruby, ORMs) cover some of the most advanced and technical ground yet, so to jump from that to the very basic of how the web works feels like a jarring slowdown. Also, the order feels kinda haphazard and out of whack, or at least the logic of the progression isn't immediately clear

**Comment by curiositypaths** [comment]
Hello there,

This lesson is meant as an introduction to the internet and an overview of basic Web Request and Response Cycle terminology.

Thank you for bringing this to our attention.
