### ISSUE TITLE
Questions about lesson content

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/how-the-web-works-readme#4]
1) Would be good to get a little bit more clarification on the response header and body. Is the screenshot just the header? (Should clarify that) Is the response body the page that loads? (Should clarify that) 

2) Section on other items included in the request is a bit confusing as well and can use slightly further explanation.

**Comment by jmburges** [comment]
closed with commit d26b564bd3b3e301fabae3777cc780c2ff1b73a0
